sudo: required
dist: trusty

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install
  - npm install -g lighthouse

env:
  - NODE_RELEASE=10.x

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

script:
  - vendor/bin/phpunit tests/

os:
  - linux

branches:
  only:
    - master

jobs:
  include:
    - stage: deploy
      php: 7.4
      script:
        - curl -s https://lucajackal85.github.io/travis-auto-tag.txt | bash